
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Make the executable
          command: |
            mvn build

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
     