
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Make the executable
          command: |
            mvn compile package

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  deploy:  
    docker:
       - image: circleci/node:7.10
    environment:    
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: Install awscli
          command:  |
              sudo apt-get update && \
              apt-get install -y \
              python3 \
              python3-pip \
              python3-setuptools \
              groff \
              less \
              && pip3 install --upgrade pip \
              && apt-get clean
              sudo pip3 --no-cache-dir install --upgrade awscli
              /bin/bash
              aws configure set aws_access_key_id AKIA2CUYMEHO3RUJ7O6P
              aws configure set aws_secret_access_key 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
              aws configure set default.region us-east-1      
      - run:
          name: Push image
          command: |
                $(aws ecr get-login --no-include-email --region us-east-1)
                docker build -t rest-api .
                docker tag rest-api:latest 692883038685.dkr.ecr.us-east-1.amazonaws.com/rest-api:latest
                docker push 692883038685.dkr.ecr.us-east-1.amazonaws.com/rest-api:latest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
